In [8]:
import pandas as pd
import numpy as np

In [9]:
data = pd.read_csv("../data/income-restricted-housing-inventory-2022.csv")
data

,Project_Name,Neighborhood,Zip Code,TtlProjUnits,RentUnits,OwnUnits,TtlMarket,MarketRent,MarketOwn,Total Income-Restricted,Income-Restricted Rental,Income-Restricted Ownership,Tenure,Public/ Private,Includes Senior Units?,Section 8
0,Abbot Street/ Shawmut Ave,Roxbury,2119.0,16,16,0,0.0,0.0,0.0,16,16,0.0,Rental,Private,NaN,NaN
1,Academy Homes I,Roxbury,2119.0,202,202,0,52.0,52.0,0.0,150,150,0.0,Rental,Private,NaN,NaN
2,Academy Homes II,Roxbury,2119.0,236,236,0,0.0,0.0,0.0,236,236,0.0,Rental,Private,NaN,Y
3,Adams Court Phase A,Mattapan,2126.0,50,50,0,0.0,0.0,0.0,50,50,0.0,Rental,Private,NaN,NaN
4,Adams Court Phase B,Mattapan,2126.0,45,45,0,0.0,0.0,0.0,45,45,0.0,Rental,Private,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1486,xxxxxxxxx Washington St,Roxbury,2130.0,10,0,10,9.0,0.0,9.0,1,0,1.0,Ownership,Private,NaN,NaN
1487,YouthBuild Ruskindale Rd,Hyde Park,2136.0,1,0,1,0.0,0.0,0.0,1,0,1.0,Ownership,Private,NaN,NaN
1488,YWCA Berkeley,South End,2116.0,208,208,0,168.0,168.0,0.0,40,40,0.0,Rental,Private,NaN,NaN
1489,YWCA Boston Units,Back Bay,2116.0,115,115,0,36.0,36.0,0.0,79,79,0.0,Rental,Private,?,NaN
1490,Zebra Condominium,South End,2118.0,10,7,3,7.0,7.0,0.0,3,0,3.0,Ownership/Rental,Private,NaN,NaN

#### Clean neighborhood column
- Fenway are listed twice, one as their own entity (`Fenway`) and one as a part of a bigger administrative body (`Fenway/Kenmore`).
- `South End` and `South end` both exist.

Turn the data into all lowercase and retain all fields that contain the neighborhood's name.

In [10]:
unique_neighborhood = data['Neighborhood'].unique()
np.sort(unique_neighborhood)

array(['Allston', 'Allston/Brighton', 'Back Bay', 'Bay Village',
       'Beacon Hill', 'Brighton', 'Central', 'Charlestown', 'Chinatown',
       'Dorchester', 'Downtown', 'East Boston', 'Fenway',
       'Fenway/Kenmore', 'Hyde Park', 'Jamaica Plain', 'Leather District',
       'Mattapan', 'Mission Hill', 'North End', 'Roslindale', 'Roxbury',
       'South Boston', 'South Boston Waterfront', 'South End',
       'South end', 'West End', 'West Roxbury'], dtype=object)

In [11]:
data['Neighborhood'] = data['Neighborhood'].str.lower()
data

,Project_Name,Neighborhood,Zip Code,TtlProjUnits,RentUnits,OwnUnits,TtlMarket,MarketRent,MarketOwn,Total Income-Restricted,Income-Restricted Rental,Income-Restricted Ownership,Tenure,Public/ Private,Includes Senior Units?,Section 8
0,Abbot Street/ Shawmut Ave,roxbury,2119.0,16,16,0,0.0,0.0,0.0,16,16,0.0,Rental,Private,NaN,NaN
1,Academy Homes I,roxbury,2119.0,202,202,0,52.0,52.0,0.0,150,150,0.0,Rental,Private,NaN,NaN
2,Academy Homes II,roxbury,2119.0,236,236,0,0.0,0.0,0.0,236,236,0.0,Rental,Private,NaN,Y
3,Adams Court Phase A,mattapan,2126.0,50,50,0,0.0,0.0,0.0,50,50,0.0,Rental,Private,NaN,NaN
4,Adams Court Phase B,mattapan,2126.0,45,45,0,0.0,0.0,0.0,45,45,0.0,Rental,Private,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1486,xxxxxxxxx Washington St,roxbury,2130.0,10,0,10,9.0,0.0,9.0,1,0,1.0,Ownership,Private,NaN,NaN
1487,YouthBuild Ruskindale Rd,hyde park,2136.0,1,0,1,0.0,0.0,0.0,1,0,1.0,Ownership,Private,NaN,NaN
1488,YWCA Berkeley,south end,2116.0,208,208,0,168.0,168.0,0.0,40,40,0.0,Rental,Private,NaN,NaN
1489,YWCA Boston Units,back bay,2116.0,115,115,0,36.0,36.0,0.0,79,79,0.0,Rental,Private,?,NaN
1490,Zebra Condominium,south end,2118.0,10,7,3,7.0,7.0,0.0,3,0,3.0,Ownership/Rental,Private,NaN,NaN

In [12]:
d7_neighborhood_list = ['roxbury', 'dorchester', 'fenway', 'south end']
d7_neighborhood_data = data[data['Neighborhood'].isin(d7_neighborhood_list)]
d7_neighborhood_data

,Project_Name,Neighborhood,Zip Code,TtlProjUnits,RentUnits,OwnUnits,TtlMarket,MarketRent,MarketOwn,Total Income-Restricted,Income-Restricted Rental,Income-Restricted Ownership,Tenure,Public/ Private,Includes Senior Units?,Section 8
0,Abbot Street/ Shawmut Ave,roxbury,2119.0,16,16,0,0.0,0.0,0.0,16,16,0.0,Rental,Private,NaN,NaN
1,Academy Homes I,roxbury,2119.0,202,202,0,52.0,52.0,0.0,150,150,0.0,Rental,Private,NaN,NaN
2,Academy Homes II,roxbury,2119.0,236,236,0,0.0,0.0,0.0,236,236,0.0,Rental,Private,NaN,Y
5,Adams Templeton Elderly Housing,dorchester,2124.0,76,76,0,1.0,1.0,0.0,75,75,0.0,Rental,Private,Y,Y
7,Alexander-Magnolia,dorchester,2125.0,40,40,0,2.0,2.0,0.0,38,38,0.0,Rental,Private,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1484,xxxxxxxx Blue Hill Ave,roxbury,2119.0,4,4,0,0.0,0.0,0.0,4,4,0.0,Rental,Private,NaN,NaN
1485,xxxxxxxx Washington St,south end,2119.0,31,0,31,27.0,0.0,27.0,4,0,4.0,Ownership,Private,NaN,NaN
1486,xxxxxxxxx Washington St,roxbury,2130.0,10,0,10,9.0,0.0,9.0,1,0,1.0,Ownership,Private,NaN,NaN
1488,YWCA Berkeley,south end,2116.0,208,208,0,168.0,168.0,0.0,40,40,0.0,Rental,Private,NaN,NaN
1490,Zebra Condominium,south end,2118.0,10,7,3,7.0,7.0,0.0,3,0,3.0,Ownership/Rental,Private,NaN,NaN

#### Examine the neighborhoods with obscurity about whether it falls under District 7 juridistiction.
- South End
- Fenway and Fenway/Kenmore

##### South End
- Manually find out which district the project belongs to from the Find My Councilor tool.
- And additional column called `D7` is appended to the CSV file to indicate whether a particular project is located in District 7. The value is 1 if the project is in D7, 0 if it doesn't, and ??? if the address cannot be determined.

In [13]:
south_end_income_restricted_housings = pd.read_csv("../data/south-end-restricted-income-housing.csv")
D7_south_end_housings = south_end_income_restricted_housings[south_end_income_restricted_housings['D7'] == '1']
D7_south_end_housings = D7_south_end_housings.drop(columns=['D7'])
D7_south_end_housings

,Project_Name,Neighborhood,Zip Code,TtlProjUnits,RentUnits,OwnUnits,TtlMarket,MarketRent,MarketOwn,Total Income-Restricted,Income-Restricted Rental,Income-Restricted Ownership,Tenure,Public/ Private,Includes Senior Units?,Section 8
2,Brownstone Apartments,south end,2118.0,75,75,0,0.0,0.0,0.0,75,75,0.0,Rental,Private,NaN,Y
8,Concord Houses,south end,2118.0,181,181,0,10.0,10.0,0.0,171,171,0.0,Rental,Private,Y,NaN
20,Frederick Douglass (2-44A),south end,2118.0,76,76,0,0.0,0.0,0.0,76,76,0.0,Rental,Public,Y,NaN
26,Historic South End Apartments,south end,2116.0,146,146,0,0.0,0.0,0.0,146,146,0.0,Rental,Private,NaN,Y
35,Langham Court,south end,2118.0,84,84,0,29.0,29.0,0.0,55,55,0.0,Rental,Private,NaN,NaN
39,Minot Hall Condominium,south end,2118.0,45,0,45,42.0,0.0,42.0,3,0,3.0,Ownership,Private,NaN,NaN
45,Rutland Square,south end,2118.0,5,5,0,0.0,0.0,0.0,5,5,0.0,Rental,Private,NaN,NaN
46,Rutland/East Springfield St (2-74),south end,2118.0,13,13,0,0.0,0.0,0.0,13,13,0.0,Rental,Public,NaN,NaN
51,South End Coop. Housing,south end,2118.0,75,75,0,2.0,2.0,0.0,73,73,0.0,Rental,Private,NaN,NaN
59,TDC III,south end,2118.0,61,61,0,46.0,46.0,0.0,15,15,0.0,Rental,Private,NaN,NaN
62,The Brownstones,south end,2116.0,35,35,0,28.0,28.0,0.0,7,7,0.0,Rental,Private,NaN,NaN
64,The Chester,south end,2118.0,17,17,0,7.0,7.0,0.0,10,10,0.0,Rental,Private,NaN,Y
75,Washington Manor (2-44C),south end,2118.0,77,77,0,0.0,0.0,0.0,77,77,0.0,Rental,Public,Y,NaN
78,West Newton Street (2-58),south end,2118.0,149,149,0,0.0,0.0,0.0,149,149,0.0,Rental,Public,NaN,NaN
84,x Columbus Ave Conversion,south end,2116.0,62,0,62,54.0,0.0,54.0,8,0,8.0,Ownership,Private,NaN,NaN
87,x Greenwich Park*,south end,2118.0,5,5,0,0.0,0.0,0.0,5,5,0.0,Rental,Private,NaN,NaN
88,x Harrison Ave,south end,2118.0,585,585,0,527.0,527.0,0.0,58,58,0.0,Rental,Private,NaN,NaN
89,x Harrison Ave Condos,south end,2118.0,39,0,39,36.0,0.0,36.0,3,0,3.0,Ownership,Private,NaN,NaN
90,x Harrison Avenue,south end,2118.0,4,0,4,3.0,0.0,3.0,1,0,1.0,Ownership/Rental,Private,NaN,NaN
98,xx Harrison Ave,south end,2118.0,84,0,84,34.0,0.0,34.0,50,0,50.0,Ownership,Private,NaN,NaN
99,xxx Harrison Ave,south end,2118.0,225,162,63,194.0,137.0,57.0,31,25,6.0,Ownership/Rental,Private,NaN,NaN
103,Zebra Condominium,south end,2118.0,10,7,3,7.0,7.0,0.0,3,0,3.0,Ownership/Rental,Private,NaN,NaN

#### Fenway
- There is only 1 ambiguous project whose neighborhood is listed as `Fenway/Kenmore`. After using the Find My Councilor tool, the project is found to not be located in District 7, so we will remove the particular row.

In [14]:
data = data[data['Neighborhood'] != "fenway/kenmore"]
data

,Project_Name,Neighborhood,Zip Code,TtlProjUnits,RentUnits,OwnUnits,TtlMarket,MarketRent,MarketOwn,Total Income-Restricted,Income-Restricted Rental,Income-Restricted Ownership,Tenure,Public/ Private,Includes Senior Units?,Section 8
0,Abbot Street/ Shawmut Ave,roxbury,2119.0,16,16,0,0.0,0.0,0.0,16,16,0.0,Rental,Private,NaN,NaN
1,Academy Homes I,roxbury,2119.0,202,202,0,52.0,52.0,0.0,150,150,0.0,Rental,Private,NaN,NaN
2,Academy Homes II,roxbury,2119.0,236,236,0,0.0,0.0,0.0,236,236,0.0,Rental,Private,NaN,Y
3,Adams Court Phase A,mattapan,2126.0,50,50,0,0.0,0.0,0.0,50,50,0.0,Rental,Private,NaN,NaN
4,Adams Court Phase B,mattapan,2126.0,45,45,0,0.0,0.0,0.0,45,45,0.0,Rental,Private,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1486,xxxxxxxxx Washington St,roxbury,2130.0,10,0,10,9.0,0.0,9.0,1,0,1.0,Ownership,Private,NaN,NaN
1487,YouthBuild Ruskindale Rd,hyde park,2136.0,1,0,1,0.0,0.0,0.0,1,0,1.0,Ownership,Private,NaN,NaN
1488,YWCA Berkeley,south end,2116.0,208,208,0,168.0,168.0,0.0,40,40,0.0,Rental,Private,NaN,NaN
1489,YWCA Boston Units,back bay,2116.0,115,115,0,36.0,36.0,0.0,79,79,0.0,Rental,Private,?,NaN
1490,Zebra Condominium,south end,2118.0,10,7,3,7.0,7.0,0.0,3,0,3.0,Ownership/Rental,Private,NaN,NaN

#### Finalize that dataset for income restricted housings in District 7

In [15]:
D7_income_restricted_housing = data[data['Neighborhood'].isin(['roxbury', 'fenway', 'dorchester'])]
D7_income_restricted_housing = pd.concat([D7_income_restricted_housing, D7_south_end_housings])
D7_income_restricted_housing

,Project_Name,Neighborhood,Zip Code,TtlProjUnits,RentUnits,OwnUnits,TtlMarket,MarketRent,MarketOwn,Total Income-Restricted,Income-Restricted Rental,Income-Restricted Ownership,Tenure,Public/ Private,Includes Senior Units?,Section 8
0,Abbot Street/ Shawmut Ave,roxbury,2119.0,16,16,0,0.0,0.0,0.0,16,16,0.0,Rental,Private,NaN,NaN
1,Academy Homes I,roxbury,2119.0,202,202,0,52.0,52.0,0.0,150,150,0.0,Rental,Private,NaN,NaN
2,Academy Homes II,roxbury,2119.0,236,236,0,0.0,0.0,0.0,236,236,0.0,Rental,Private,NaN,Y
5,Adams Templeton Elderly Housing,dorchester,2124.0,76,76,0,1.0,1.0,0.0,75,75,0.0,Rental,Private,Y,Y
7,Alexander-Magnolia,dorchester,2125.0,40,40,0,2.0,2.0,0.0,38,38,0.0,Rental,Private,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,x Harrison Ave Condos,south end,2118.0,39,0,39,36.0,0.0,36.0,3,0,3.0,Ownership,Private,NaN,NaN
90,x Harrison Avenue,south end,2118.0,4,0,4,3.0,0.0,3.0,1,0,1.0,Ownership/Rental,Private,NaN,NaN
98,xx Harrison Ave,south end,2118.0,84,0,84,34.0,0.0,34.0,50,0,50.0,Ownership,Private,NaN,NaN
99,xxx Harrison Ave,south end,2118.0,225,162,63,194.0,137.0,57.0,31,25,6.0,Ownership/Rental,Private,NaN,NaN
103,Zebra Condominium,south end,2118.0,10,7,3,7.0,7.0,0.0,3,0,3.0,Ownership/Rental,Private,NaN,NaN

#### Export to CSV

In [16]:
D7_income_restricted_housing.to_csv("../data/d7-income-restricted-housing.csv", index=False)