### Datasets from Census.gov, deagregating housing units by demographic information - for the years 2011 - 2022 - for District 7

In [1]:
import pandas as pd

df_2011 = pd.read_csv(r"../data/demographic-information/district_7/ACSST5Y2011.S2502-Data.csv")
df_2012 = pd.read_csv(r"../data/demographic-information/district_7/ACSST5Y2012.S2502-Data.csv")
df_2013 = pd.read_csv(r"../data/demographic-information/district_7/ACSST5Y2013.S2502-Data.csv")
df_2014 = pd.read_csv(r"../data/demographic-information/district_7/ACSST5Y2014.S2502-Data.csv")
df_2015 = pd.read_csv(r"../data/demographic-information/district_7/ACSST5Y2015.S2502-Data.csv")
df_2016 = pd.read_csv(r"../data/demographic-information/district_7/ACSST5Y2016.S2502-Data.csv")
df_2017 = pd.read_csv(r"../data/demographic-information/district_7/ACSST5Y2017.S2502-Data.csv")
df_2018 = pd.read_csv(r"../data/demographic-information/district_7/ACSST5Y2018.S2502-Data.csv")
df_2019 = pd.read_csv(r"../data/demographic-information/district_7/ACSST5Y2019.S2502-Data.csv")
df_2020 = pd.read_csv(r"../data/demographic-information/district_7/ACSST5Y2020.S2502-Data.csv")
df_2021 = pd.read_csv(r"../data/demographic-information/district_7/ACSST5Y2021.S2502-Data.csv")
df_2022 = pd.read_csv(r"../data/demographic-information/district_7/ACSST5Y2022.S2502-Data.csv")

print("CSV files loaded successfully.")

CSV files loaded successfully.

In [195]:
print(df_2011.columns)

Index(['GEO_ID', 'NAME', 'S2502_C01_001E', 'S2502_C01_001M', 'S2502_C02_001E',
       'S2502_C02_001M', 'S2502_C03_001E', 'S2502_C03_001M', 'S2502_C01_002E',
       'S2502_C01_002M',
       ...
       'S2502_C02_027M', 'S2502_C03_027E', 'S2502_C03_027M', 'S2502_C01_028E',
       'S2502_C01_028M', 'S2502_C02_028E', 'S2502_C02_028M', 'S2502_C03_028E',
       'S2502_C03_028M', 'Unnamed: 170'],
      dtype='object', length=171)

In [196]:
df_2011

,GEO_ID,NAME,S2502_C01_001E,S2502_C01_001M,S2502_C02_001E,S2502_C02_001M,S2502_C03_001E,S2502_C03_001M,S2502_C01_002E,S2502_C01_002M,...,S2502_C02_027M,S2502_C03_027E,S2502_C03_027M,S2502_C01_028E,S2502_C01_028M,S2502_C02_028E,S2502_C02_028M,S2502_C03_028E,S2502_C03_028M,Unnamed: 170
0,Geography,Geographic Area Name,Occupied housing units!!Estimate!!Occupied hou...,Occupied housing units!!Margin of Error!!Occup...,Owner-occupied housing units!!Estimate!!Occupi...,Owner-occupied housing units!!Margin of Error!...,Renter-occupied housing units!!Estimate!!Occup...,Renter-occupied housing units!!Margin of Error...,Occupied housing units!!Estimate!!RACE AND HIS...,Occupied housing units!!Margin of Error!!RACE ...,...,Owner-occupied housing units!!Margin of Error!...,Renter-occupied housing units!!Estimate!!PERCE...,Renter-occupied housing units!!Margin of Error...,Occupied housing units!!Estimate!!PERCENT IMPU...,Occupied housing units!!Margin of Error!!PERCE...,Owner-occupied housing units!!Estimate!!PERCEN...,Owner-occupied housing units!!Margin of Error!...,Renter-occupied housing units!!Estimate!!PERCE...,Renter-occupied housing units!!Margin of Error...,NaN
1,1400000US25025010300,"Census Tract 103, Suffolk County, Massachusetts",262,48,62,20,200,53,83.2,9.6,...,(X),(X),(X),0.0,(X),(X),(X),(X),(X),NaN
2,1400000US25025010403,"Census Tract 104.03, Suffolk County, Massachus...",1896,131,63,50,1833,138,53.1,9.2,...,(X),(X),(X),7.6,(X),(X),(X),(X),(X),NaN
3,1400000US25025010404,"Census Tract 104.04, Suffolk County, Massachus...",1658,145,125,60,1533,154,71.3,8.7,...,(X),(X),(X),0.0,(X),(X),(X),(X),(X),NaN
4,1400000US25025010405,"Census Tract 104.05, Suffolk County, Massachus...",986,68,62,28,924,74,66.4,8.3,...,(X),(X),(X),2.5,(X),(X),(X),(X),(X),NaN
5,1400000US25025010500,"Census Tract 105, Suffolk County, Massachusetts",1661,103,167,50,1494,114,69.0,6.5,...,(X),(X),(X),0.8,(X),(X),(X),(X),(X),NaN
6,1400000US25025010600,"Census Tract 106, Suffolk County, Massachusetts",1736,133,335,101,1401,139,83.9,5.5,...,(X),(X),(X),4.4,(X),(X),(X),(X),(X),NaN
7,1400000US25025010701,"Census Tract 107.01, Suffolk County, Massachus...",1470,141,415,104,1055,161,82.1,9.1,...,(X),(X),(X),1.2,(X),(X),(X),(X),(X),NaN
8,1400000US25025070600,"Census Tract 706, Suffolk County, Massachusetts",1329,81,744,129,585,138,81.7,8.2,...,(X),(X),(X),0.9,(X),(X),(X),(X),(X),NaN
9,1400000US25025070700,"Census Tract 707, Suffolk County, Massachusetts",1244,90,417,108,827,112,60.0,7.2,...,(X),(X),(X),1.2,(X),(X),(X),(X),(X),NaN
10,1400000US25025071101,"Census Tract 711.01, Suffolk County, Massachus...",2095,96,546,110,1549,137,47.0,6.6,...,(X),(X),(X),1.9,(X),(X),(X),(X),(X),NaN
11,1400000US25025080100,"Census Tract 801, Suffolk County, Massachusetts",613,69,264,76,349,86,16.0,7.5,...,(X),(X),(X),0.0,(X),(X),(X),(X),(X),NaN
12,1400000US25025080300,"Census Tract 803, Suffolk County, Massachusetts",761,97,126,83,635,103,15.5,10.3,...,(X),(X),(X),9.9,(X),(X),(X),(X),(X),NaN
13,1400000US25025080401,"Census Tract 804.01, Suffolk County, Massachus...",1163,111,145,59,1018,110,12.1,5.8,...,(X),(X),(X),7.5,(X),(X),(X),(X),(X),NaN
14,1400000US25025080500,"Census Tract 805, Suffolk County, Massachusetts",1264,88,45,51,1219,90,18.0,8.4,...,(X),(X),(X),3.7,(X),(X),(X),(X),(X),NaN
15,1400000US25025080601,"Census Tract 806.01, Suffolk County, Massachus...",843,90,90,60,753,88,33.6,11.4,...,(X),(X),(X),3.3,(X),(X),(X),(X),(X),NaN
16,1400000US25025080801,"Census Tract 808.01, Suffolk County, Massachus...",950,57,25,28,925,64,15.2,7.7,...,(X),(X),(X),4.0,(X),(X),(X),(X),(X),NaN
17,1400000US25025081400,"Census Tract 814, Suffolk County, Massachusetts",1246,115,463,136,783,143,23.3,7.5,...,(X),(X),(X),4.1,(X),(X),(X),(X),(X),NaN
18,1400000US25025081500,"Census Tract 815, Suffolk County, Massachusetts",814,66,305,73,509,89,13.6,5.8,...,(X),(X),(X),5.5,(X),(X),(X),(X),(X),NaN
19,1400000US25025081700,"Census Tract 817, Suffolk County, Massachusetts",1423,102,323,111,1100,131,6.5,4.5,...,(X),(X),(X),1.5,(X),(X),(X),(X),(X),NaN
20,1400000US25025081800,"Census Tract 818, Suffolk County, Massachusetts",1104,149,424,132,680,134,11.8,6.7,...,(X),(X),(X),4.8,(X),(X),(X),(X),(X),NaN
21,1400000US25025081900,"Census Tract 819, Suffolk County, Massachusetts",1177,124,261,84,916,147,7.8,6.8,...,(X),(X),(X),4.2,(X),(X),(X),(X),(X),NaN
22,1400000US25025082000,"Census Tract 820, Suffolk County, Massachusetts",1072,103,380,88,692,114,9.4,6.9,...,(X),(X),(X),7.8,(X),(X),(X),(X),(X),NaN
23,1400000US25025082100,"Census Tract 821, Suffolk County, Massachusetts",2017,121,293,100,1724,150,13.1,4.6,...,(X),(X),(X),7.5,(X),(X),(X),(X),(X),NaN
24,1400000US25025090300,"Census Tract 903, Suffolk County, Massachusetts",967,118,218,73,749,122,10.3,5.9,...,(X),(X),(X),3.4,(X),(X),(X),(X),(X),NaN
25,1400000US25025090400,"Census Tract 904, Suffolk County, Massachusetts",1064,96,290,93,774,120,6.7,4.7,...,(X),(X),(X),0.8,(X),(X),(X),(X),(X),NaN
26,1400000US25025090600,"Census Tract 906, Suffolk County, Massachusetts",660,82,261,97,399,113,12.7,8.2,...,(X),(X),(X),3.5,(X),(X),(X),(X),(X),NaN
27,1400000US25025091300,"Census Tract 913, Suffolk County, Massachusetts",649,97,160,62,489,98,16.5,10.3,...,(X),(X),(X),0.0,(X),(X),(X),(X),(X),NaN
28,1400000US25025091400,"Census Tract 914, Suffolk County, Massachusetts",847,74,278,79,569,86,13.5,7.5,...,(X),(X),(X),6.4,(X),(X),(X),(X),(X),NaN
29,1400000US25025120201,"Census Tract 1202.01, Suffolk County, Massachu...",1688,81,536,112,1152,115,69.3,7.5,...,(X),(X),(X),4.4,(X),(X),(X),(X),(X),NaN
30,1400000US25025120301,"Census Tract 1203.01, Suffolk County, Massachu...",1817,107,951,122,866,144,54.9,7.7,...,(X),(X),(X),2.5,(X),(X),(X),(X),(X),NaN
31,1400000US25025980300,"Census Tract 9803, Suffolk County, Massachusetts",12,15,0,95,12,15,100.0,92.0,...,(X),(X),(X),0.0,(X),(X),(X),(X),(X),NaN

In [197]:
import pandas as pd

# Function to remove the last column of the dataframe
def remove_last_column(df):
    df = df.iloc[:, :-1]
    return df

# Function to replace column names with the first row of the dataframe
def replace_column_names_with_first_row(df):
    df.columns = df.iloc[0]
    df = df[1:]
    return df

# Function to convert all columns with numbers in them to numeric
def convert_columns_to_numeric(df):
    df = df.apply(pd.to_numeric, errors='coerce')
    return df

# Function to remove columns containing specific words in the column name
def remove_specific_columns(df):
    columns_to_drop = df.filter(regex='Geograph|PERCENT|Margin of Error|Percent|Moved In|Moved in').columns
    df = df.drop(columns=columns_to_drop)
    return df

# Function to aggregate all rows of each column to sum them
def aggregate_rows(df):
    aggregated_df = df.sum(numeric_only=True).to_frame().T
    return aggregated_df

# Function to process the dataframe according to the specified steps
def process_dataframe(df):
    df = remove_last_column(df)
    df = replace_column_names_with_first_row(df)
    df = convert_columns_to_numeric(df)
    df = remove_specific_columns(df)
    df = aggregate_rows(df)
    return df


# Apply the processing function to each dataframe
df_2011_processed = process_dataframe(df_2011)
df_2012_processed = process_dataframe(df_2012)
df_2013_processed = process_dataframe(df_2013)
df_2014_processed = process_dataframe(df_2014)
df_2015_processed = process_dataframe(df_2015)
df_2016_processed = process_dataframe(df_2016)
df_2017_processed = process_dataframe(df_2017)
df_2018_processed = process_dataframe(df_2018)
df_2019_processed = process_dataframe(df_2019)
df_2020_processed = process_dataframe(df_2020)
df_2021_processed = process_dataframe(df_2021)
df_2022_processed = process_dataframe(df_2022)

print("Processing complete for all dataframes.")

Processing complete for all dataframes.

In [198]:
df_2019_processed.head()

,Estimate!!Occupied housing units!!Occupied housing units,Estimate!!Occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!White,Estimate!!Occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!Black or African American,Estimate!!Occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!American Indian and Alaska Native,Estimate!!Occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!Asian,Estimate!!Occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!Native Hawaiian and Other Pacific Islander,Estimate!!Occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!Some other race,Estimate!!Occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Two or more races,Estimate!!Occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Hispanic or Latino origin,"Estimate!!Occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!White alone, not Hispanic or Latino",...,Estimate!!Renter-occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!35 to 44 years,Estimate!!Renter-occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!45 to 54 years,Estimate!!Renter-occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!55 to 64 years,Estimate!!Renter-occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!65 to 74 years,Estimate!!Renter-occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!75 to 84 years,Estimate!!Renter-occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!85 years and over,Estimate!!Renter-occupied housing units!!Occupied housing units!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Less than high school graduate,Estimate!!Renter-occupied housing units!!Occupied housing units!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!High school graduate (includes equivalency),Estimate!!Renter-occupied housing units!!Occupied housing units!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Some college or associate's degree,Estimate!!Renter-occupied housing units!!Occupied housing units!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Bachelor's degree or higher
0,39343,14880,15153,221,2915,101,4526,1547,9168,12262,...,4982,4822,4429,2913,1489,501,5503,6821,6970,10293

In [199]:
df_2011_processed.columns

Index(['Occupied housing units!!Estimate!!Occupied housing units',
       'Owner-occupied housing units!!Estimate!!Occupied housing units',
       'Renter-occupied housing units!!Estimate!!Occupied housing units',
       'Occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!White',
       'Owner-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!White',
       'Renter-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!White',
       'Occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Black or African American',
       'Owner-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Black or African American',
       'Renter-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Black or African American',
       'Occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!American Indian and Alaska Native',
       'Owner-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!American Indian and Alaska Native',
       'Renter-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!American Indian and Alaska Native',
       'Occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Asian',
       'Owner-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Asian',
       'Renter-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Asian',
       'Occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Native Hawaiian and Other Pacific Islander',
       'Owner-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Native Hawaiian and Other Pacific Islander',
       'Renter-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Native Hawaiian and Other Pacific Islander',
       'Occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Some other race',
       'Owner-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Some other race',
       'Renter-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Some other race',
       'Occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Two or more races',
       'Owner-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Two or more races',
       'Renter-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Two or more races',
       'Occupied housing units!!Estimate!!Hispanic or Latino origin',
       'Owner-occupied housing units!!Estimate!!Hispanic or Latino origin',
       'Renter-occupied housing units!!Estimate!!Hispanic or Latino origin',
       'Occupied housing units!!Estimate!!White alone, not Hispanic or Latino',
       'Owner-occupied housing units!!Estimate!!White alone, not Hispanic or Latino',
       'Renter-occupied housing units!!Estimate!!White alone, not Hispanic or Latino',
       'Occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!Under 35 years',
       'Owner-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!Under 35 years',
       'Renter-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!Under 35 years',
       'Occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!35 to 44 years',
       'Owner-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!35 to 44 years',
       'Renter-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!35 to 44 years',
       'Occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!45 to 54 years',
       'Owner-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!45 to 54 years',
       'Renter-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!45 to 54 years',
       'Occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!55 to 64 years',
       'Owner-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!55 to 64 years',
       'Renter-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!55 to 64 years',
       'Occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!65 to 74 years',
       'Owner-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!65 to 74 years',
       'Renter-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!65 to 74 years',
       'Occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!75 to 84 years',
       'Owner-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!75 to 84 years',
       'Renter-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!75 to 84 years',
       'Occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!85 years and over',
       'Owner-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!85 years and over',
       'Renter-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!85 years and over',
       'Occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Less than high school graduate',
       'Owner-occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Less than high school graduate',
       'Renter-occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Less than high school graduate',
       'Occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!High school graduate (includes equivalency)',
       'Owner-occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!High school graduate (includes equivalency)',
       'Renter-occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!High school graduate (includes equivalency)',
       'Occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Some college or associate's degree',
       'Owner-occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Some college or associate's degree',
       'Renter-occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Some college or associate's degree',
       'Occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Bachelor's degree or higher',
       'Owner-occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Bachelor's degree or higher',
       'Renter-occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Bachelor's degree or higher'],
      dtype='object', name=0)

As can be seen, the dataset columns have terrible names, so renaming them for better readability. This has to be done twice because the datasets from 2011-2018 have columns with certain kinds of names, and the datasets from 2019-2022 have columns with different kinds of names.

In [200]:
def rename_columns(df):
    # Define the column renaming mapping
    column_mapping = {
        'Estimate!!Occupied housing units!!Occupied housing units': 'Occupied Housing Units',
        'Estimate!!Occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!White': 'Occupied: White',
        'Estimate!!Occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!Black or African American' : 'Occupied: Black or African American',
        'Estimate!!Occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!American Indian and Alaska Native' : 'Occupied: American Indian and Alaskan Native',
        'Estimate!!Occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!Asian' : "Occupied: Asian",
        "Estimate!!Occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!Native Hawaiian and Other Pacific Islander" : "Occupied: Native Hawaiian and Other Pacific Islander",
        "Estimate!!Occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!Some other race" : "Occupied: Some Other Race",
        "Estimate!!Occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Two or more races" : "Occupied: Two or more races",
        "Estimate!!Occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Hispanic or Latino origin" : "Occupied: Hispanic or Latino Origin",
        "Estimate!!Occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!White alone, not Hispanic or Latino" : "Occupied: White Alone (Not Hispanic or Latino)",
        'Estimate!!Occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!Under 35 years' : "Occupied: < 35 years", 
        'Estimate!!Occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!35 to 44 years' : "Occupied: 35-44 years",
       'Estimate!!Occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!45 to 54 years' : "Occupied: 45-54 years",
       'Estimate!!Occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!55 to 64 years' : "Occupied: 55-64 years",
       'Estimate!!Occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!65 to 74 years' : "Occupied: 65-74 years",
       'Estimate!!Occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!75 to 84 years' : "Occupied: 75-84 years",
       'Estimate!!Occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!85 years and over' : "Occupied: > 85 years",
       'Estimate!!Occupied housing units!!Occupied housing units!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Less than high school graduate' : "Occupied: Less than High School",
       'Estimate!!Occupied housing units!!Occupied housing units!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!High school graduate (includes equivalency)': "Occupied: High School Graduate",
       "Estimate!!Occupied housing units!!Occupied housing units!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Some college or associate's degree" : "Occupied: Some college or associates degree",
       "Estimate!!Occupied housing units!!Occupied housing units!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Bachelor's degree or higher" : "Occupied: Bachelor's degree or higher",
       'Estimate!!Occupied housing units!!Occupied housing units!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 2017 or later' : "Occupied: Moved in 2017 or later",
       'Estimate!!Occupied housing units!!Occupied housing units!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 2015 to 2016' : "Occupied: Moved in 2015 to 2016",
       'Estimate!!Occupied housing units!!Occupied housing units!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 2010 to 2014' : "Occupied: Moved in 2010 to 2014",
       'Estimate!!Occupied housing units!!Occupied housing units!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 2000 to 2009' : "Occupied: Moved in 2000 to 2009",
       'Estimate!!Occupied housing units!!Occupied housing units!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 1990 to 1999' : "Occupied: Moved in 1990 to 1999",
       'Estimate!!Occupied housing units!!Occupied housing units!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 1989 or earlier' : "Occupied: Moved in 1989 or earlier",
       'Estimate!!Owner-occupied housing units!!Occupied housing units' : "Owner Occupied Housing Units",
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!White' : 'Owner Occupied: White',
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!Black or African American': 'Owner Occupied: Black or African American',
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!American Indian and Alaska Native' : 'Owner Occupied: American Indian and Alaskan Native',
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!Asian': "Owner Occupied: Asian",
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!Native Hawaiian and Other Pacific Islander' : "Owner Occupied: Native Hawaiian and Other Pacific Islander",
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!Some other race' : "Owner Occupied: Some Other Race",
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Two or more races' : "Owner Occupied: Two or more races",
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Hispanic or Latino origin': "Owner Occupied: Hispanic or Latino Origin",
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!White alone, not Hispanic or Latino' : "Owner Occupied: White Alone (Not Hispanic or Latino)",
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!Under 35 years' : "Owner Occupied: < 35 years",
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!35 to 44 years' : "Owner Occupied: 35-44 years",
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!45 to 54 years' : "Owner Occupied: 45-54 years",
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!55 to 64 years' : "Owner Occupied: 55-64 years",
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!65 to 74 years' : "Owner Occupied: 65-74 years",
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!75 to 84 years' : "Owner Occupied: 75-84 years",
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!85 years and over' : "Owner Occupied: > 85 years",
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Less than high school graduate' : "Owner Occupied: Less than High School",
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!High school graduate (includes equivalency)' : "Owner Occupied: High School Graduate",
       "Estimate!!Owner-occupied housing units!!Occupied housing units!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Some college or associate's degree" : "Owner Occupied: Some college or associates degree",
       "Estimate!!Owner-occupied housing units!!Occupied housing units!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Bachelor's degree or higher" : "Owner Occupied: Bachelor's degree or higher",
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 2017 or later' : "Owner Occupied: Moved in 2017 or later",
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 2015 to 2016' : "Owner Occupied: Moved in 2015 to 2016",
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 2010 to 2014' : "Owner Occupied: Moved in 2010 to 2014",
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 2000 to 2009' : "Owner Occupied: Moved in 2000 to 2009",
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 1990 to 1999' : "Owner Occupied: Moved in 1990 to 1999",
       'Estimate!!Owner-occupied housing units!!Occupied housing units!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 1989 or earlier' : "Owner Occupied: Moved in 1989 or earlier",
       'Estimate!!Renter-occupied housing units!!Occupied housing units' : "Renter Occupied Housing Units",
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!White'  : 'Renter Occupied: White',
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!Black or African American' : 'Renter Occupied: Black or African American',
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!American Indian and Alaska Native' : 'Renter Occupied: American Indian and Alaskan Native',
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!Asian' : "Renter Occupied: Asian",
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!Native Hawaiian and Other Pacific Islander' : "Renter Occupied: Native Hawaiian and Other Pacific Islander",
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race --!!Some other race' : "Renter Occupied: Some Other Race",
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Two or more races' : "Renter Occupied: Two or more races",
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Hispanic or Latino origin' : "Renter Occupied: Hispanic or Latino Origin" ,
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!White alone, not Hispanic or Latino' : "Renter Occupied: White Alone (Not Hispanic or Latino)",
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!Under 35 years' : "Renter Occupied: < 35 years",
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!35 to 44 years' : "Renter Occupied: 35-44 years",
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!45 to 54 years' : "Renter Occupied: 45-54 years",
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!55 to 64 years' : "Renter Occupied: 55-64 years",
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!65 to 74 years' : "Renter Occupied: 65-74 years",
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!75 to 84 years' : "Renter Occupied: 75-84 years",
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!AGE OF HOUSEHOLDER!!85 years and over' : "Renter Occupied: > 85 years",
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Less than high school graduate' : "Renter Occupied: Less than High School",
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!High school graduate (includes equivalency)' : "Renter Occupied: High School Graduate",
       "Estimate!!Renter-occupied housing units!!Occupied housing units!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Some college or associate's degree" : "Renter Occupied: Some college or associates degree",
       "Estimate!!Renter-occupied housing units!!Occupied housing units!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Bachelor's degree or higher" : "Renter Occupied: Bachelor's degree or higher",
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 2017 or later' : "Renter Occupied: Moved in 2017 or later",
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 2015 to 2016' : "Renter Occupied: Moved in 2015 to 2016",
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 2010 to 2014' : "Renter Occupied: Moved in 2010 to 2014",
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 2000 to 2009' : "Renter Occupied: Moved in 2000 to 2009",
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 1990 to 1999' : "Renter Occupied: Moved in 1990 to 1999",
       'Estimate!!Renter-occupied housing units!!Occupied housing units!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 1989 or earlier' : "Renter Occupied: Moved in 1989 or earlier"
    }
    
    # Rename the columns
    df = df.rename(columns=column_mapping)
    
    return df

In [201]:
def rename_columns_type2(df):
    column_mapping = {
        'Occupied housing units!!Estimate!!Occupied housing units': 'Occupied Housing Units',
        'Owner-occupied housing units!!Estimate!!Occupied housing units': 'Owner Occupied Housing Units',
        'Renter-occupied housing units!!Estimate!!Occupied housing units': 'Renter Occupied Housing Units',
        'Occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!White': 'Occupied: White',
        'Owner-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!White': 'Owner Occupied: White',
        'Renter-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!White': 'Renter Occupied: White',
        'Occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Black or African American': 'Occupied: Black or African American',
        'Owner-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Black or African American': 'Owner Occupied: Black or African American',
        'Renter-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Black or African American': 'Renter Occupied: Black or African American',
        'Occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!American Indian and Alaska Native': 'Occupied: American Indian and Alaskan Native',
        'Owner-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!American Indian and Alaska Native': 'Owner Occupied: American Indian and Alaskan Native',
        'Renter-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!American Indian and Alaska Native': 'Renter Occupied: American Indian and Alaskan Native',
        'Occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Asian': 'Occupied: Asian',
        'Owner-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Asian': 'Owner Occupied: Asian',
        'Renter-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Asian': 'Renter Occupied: Asian',
        'Occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Native Hawaiian and Other Pacific Islander': 'Occupied: Native Hawaiian and Other Pacific Islander',
        'Owner-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Native Hawaiian and Other Pacific Islander': 'Owner Occupied: Native Hawaiian and Other Pacific Islander',
        'Renter-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Native Hawaiian and Other Pacific Islander': 'Renter Occupied: Native Hawaiian and Other Pacific Islander',
        'Occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Some other race': 'Occupied: Some Other Race',
        'Owner-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Some other race': 'Owner Occupied: Some Other Race',
        'Renter-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!One race!!Some other race': 'Renter Occupied: Some Other Race',
        'Occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Two or more races': 'Occupied: Two or more races',
        'Owner-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Two or more races': 'Owner Occupied: Two or more races',
        'Renter-occupied housing units!!Estimate!!RACE AND HISPANIC OR LATINO ORIGIN OF HOUSEHOLDER!!Two or more races': 'Renter Occupied: Two or more races',
        'Occupied housing units!!Estimate!!Hispanic or Latino origin': 'Occupied: Hispanic or Latino Origin',
        'Owner-occupied housing units!!Estimate!!Hispanic or Latino origin': 'Owner Occupied: Hispanic or Latino Origin',
        'Renter-occupied housing units!!Estimate!!Hispanic or Latino origin': 'Renter Occupied: Hispanic or Latino Origin',
        'Occupied housing units!!Estimate!!White alone, not Hispanic or Latino': 'Occupied: White Alone (Not Hispanic or Latino)',
        'Owner-occupied housing units!!Estimate!!White alone, not Hispanic or Latino': 'Owner Occupied: White Alone (Not Hispanic or Latino)',
        'Renter-occupied housing units!!Estimate!!White alone, not Hispanic or Latino': 'Renter Occupied: White Alone (Not Hispanic or Latino)',
        'Occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!Under 35 years': 'Occupied: < 35 years',
        'Owner-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!Under 35 years': 'Owner Occupied: < 35 years',
        'Renter-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!Under 35 years': 'Renter Occupied: < 35 years',
        'Occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!35 to 44 years': 'Occupied: 35-44 years',
        'Owner-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!35 to 44 years': 'Owner Occupied: 35-44 years',
        'Renter-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!35 to 44 years': 'Renter Occupied: 35-44 years',
        'Occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!45 to 54 years': 'Occupied: 45-54 years',
        'Owner-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!45 to 54 years': 'Owner Occupied: 45-54 years',
        'Renter-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!45 to 54 years': 'Renter Occupied: 45-54 years',
        'Occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!55 to 64 years': 'Occupied: 55-64 years',
        'Owner-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!55 to 64 years': 'Owner Occupied: 55-64 years',
        'Renter-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!55 to 64 years': 'Renter Occupied: 55-64 years',
        'Occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!65 to 74 years': 'Occupied: 65-74 years',
        'Owner-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!65 to 74 years': 'Owner Occupied: 65-74 years',
        'Renter-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!65 to 74 years': 'Renter Occupied: 65-74 years',
        'Occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!75 to 84 years': 'Occupied: 75-84 years',
        'Owner-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!75 to 84 years': 'Owner Occupied: 75-84 years',
        'Renter-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!75 to 84 years': 'Renter Occupied: 75-84 years',
        'Occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!85 years and over': 'Occupied: > 85 years',
        'Owner-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!85 years and over': 'Owner Occupied: > 85 years',
        'Renter-occupied housing units!!Estimate!!AGE OF HOUSEHOLDER!!85 years and over': 'Renter Occupied: > 85 years',
        'Occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Less than high school graduate': 'Occupied: Less than High School',
        'Owner-occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Less than high school graduate': 'Owner Occupied: Less than High School',
        'Renter-occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Less than high school graduate': 'Renter Occupied: Less than High School',
        'Occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!High school graduate (includes equivalency)': 'Occupied: High School Graduate',
        'Owner-occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!High school graduate (includes equivalency)': 'Owner Occupied: High School Graduate',
        'Renter-occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!High school graduate (includes equivalency)': 'Renter Occupied: High School Graduate',
        'Occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Some college or associate\'s degree': 'Occupied: Some college or associates degree',
        'Owner-occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Some college or associate\'s degree': 'Owner Occupied: Some college or associates degree',
        'Renter-occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Some college or associate\'s degree': 'Renter Occupied: Some college or associates degree',
        'Occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Bachelor\'s degree or higher': 'Occupied: Bachelor\'s degree or higher',
        "Owner-occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Bachelor\'s degree or higher": "Owner Occupied: Bachelor's degree or higher",
        'Renter-occupied housing units!!Estimate!!EDUCATIONAL ATTAINMENT OF HOUSEHOLDER!!Bachelor\'s degree or higher': "Renter Occupied: Bachelor's degree or higher",
        'Occupied housing units!!Estimate!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 2000 or later': 'Occupied: Moved in 2000 or later',
        'Owner-occupied housing units!!Estimate!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 2000 or later': 'Owner Occupied: Moved in 2000 or later',
        'Renter-occupied housing units!!Estimate!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 2000 or later': 'Renter Occupied: Moved in 2000 or later',
        'Occupied housing units!!Estimate!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 1990 to 1999': 'Occupied: Moved in 1990 to 1999',
        'Owner-occupied housing units!!Estimate!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 1990 to 1999': 'Owner Occupied: Moved in 1990 to 1999',
        'Renter-occupied housing units!!Estimate!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 1990 to 1999': 'Renter Occupied: Moved in 1990 to 1999',
        'Occupied housing units!!Estimate!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 1980 to 1989': 'Occupied: Moved in 1980 to 1989',
        'Owner-occupied housing units!!Estimate!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 1980 to 1989': 'Owner Occupied: Moved in 1980 to 1989',
        'Renter-occupied housing units!!Estimate!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 1980 to 1989': 'Renter Occupied: Moved in 1980 to 1989',
        'Occupied housing units!!Estimate!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 1970 to 1979': 'Occupied: Moved in 1970 to 1979',
        'Owner-occupied housing units!!Estimate!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 1970 to 1979': 'Owner Occupied: Moved in 1970 to 1979',
        'Renter-occupied housing units!!Estimate!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 1970 to 1979': 'Renter Occupied: Moved in 1970 to 1979',
        'Occupied housing units!!Estimate!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 1969 or earlier': 'Occupied: Moved in 1969 or earlier',
        'Owner-occupied housing units!!Estimate!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 1969 or earlier': 'Owner Occupied: Moved in 1969 or earlier',
        'Renter-occupied housing units!!Estimate!!YEAR HOUSEHOLDER MOVED INTO UNIT!!Moved in 1969 or earlier': 'Renter Occupied: Moved in 1969 or earlier'


    }
    
    df = df.rename(columns=column_mapping)
    return df

"""# Apply the rename_columns_type2 function to each dataset
df_2011_processed = rename_columns_type2(df_2011_processed)
df_2012_processed = rename_columns_type2(df_2012_processed)
df_2013_processed = rename_columns_type2(df_2013_processed)
df_2014_processed = rename_columns_type2(df_2014_processed)
df_2015_processed = rename_columns_type2(df_2015_processed)
df_2016_processed = rename_columns_type2(df_2016_processed)
df_2017_processed = rename_columns_type2(df_2017_processed)
df_2018_processed = rename_columns_type2(df_2018_processed)
df_2019_processed = rename_columns_type2(df_2019_processed)
df_2020_processed = rename_columns_type2(df_2020_processed)
df_2021_processed = rename_columns_type2(df_2021_processed)
df_2022_processed = rename_columns_type2(df_2022_processed)"""

'# Apply the rename_columns_type2 function to each dataset\ndf_2011_processed = rename_columns_type2(df_2011_processed)\ndf_2012_processed = rename_columns_type2(df_2012_processed)\ndf_2013_processed = rename_columns_type2(df_2013_processed)\ndf_2014_processed = rename_columns_type2(df_2014_processed)\ndf_2015_processed = rename_columns_type2(df_2015_processed)\ndf_2016_processed = rename_columns_type2(df_2016_processed)\ndf_2017_processed = rename_columns_type2(df_2017_processed)\ndf_2018_processed = rename_columns_type2(df_2018_processed)\ndf_2019_processed = rename_columns_type2(df_2019_processed)\ndf_2020_processed = rename_columns_type2(df_2020_processed)\ndf_2021_processed = rename_columns_type2(df_2021_processed)\ndf_2022_processed = rename_columns_type2(df_2022_processed)'

In [202]:
df_2011_processed = rename_columns_type2(rename_columns(df_2011_processed))
df_2012_processed = rename_columns_type2(rename_columns(df_2012_processed))
df_2013_processed = rename_columns_type2(rename_columns(df_2013_processed))
df_2014_processed = rename_columns_type2(rename_columns(df_2014_processed))
df_2015_processed = rename_columns_type2(rename_columns(df_2015_processed))
df_2016_processed = rename_columns_type2(rename_columns(df_2016_processed))
df_2017_processed = rename_columns_type2(rename_columns(df_2017_processed))
df_2018_processed = rename_columns_type2(rename_columns(df_2018_processed))
df_2019_processed = rename_columns_type2(rename_columns(df_2019_processed))
df_2020_processed = rename_columns_type2(rename_columns(df_2020_processed))
df_2021_processed = rename_columns_type2(rename_columns(df_2021_processed))
df_2022_processed = rename_columns_type2(rename_columns(df_2022_processed))

In [203]:
df_2011_processed.columns

Index(['Occupied Housing Units', 'Owner Occupied Housing Units',
       'Renter Occupied Housing Units', 'Occupied: White',
       'Owner Occupied: White', 'Renter Occupied: White',
       'Occupied: Black or African American',
       'Owner Occupied: Black or African American',
       'Renter Occupied: Black or African American',
       'Occupied: American Indian and Alaskan Native',
       'Owner Occupied: American Indian and Alaskan Native',
       'Renter Occupied: American Indian and Alaskan Native',
       'Occupied: Asian', 'Owner Occupied: Asian', 'Renter Occupied: Asian',
       'Occupied: Native Hawaiian and Other Pacific Islander',
       'Owner Occupied: Native Hawaiian and Other Pacific Islander',
       'Renter Occupied: Native Hawaiian and Other Pacific Islander',
       'Occupied: Some Other Race', 'Owner Occupied: Some Other Race',
       'Renter Occupied: Some Other Race', 'Occupied: Two or more races',
       'Owner Occupied: Two or more races',
       'Renter Occupied: Two or more races',
       'Occupied: Hispanic or Latino Origin',
       'Owner Occupied: Hispanic or Latino Origin',
       'Renter Occupied: Hispanic or Latino Origin',
       'Occupied: White Alone (Not Hispanic or Latino)',
       'Owner Occupied: White Alone (Not Hispanic or Latino)',
       'Renter Occupied: White Alone (Not Hispanic or Latino)',
       'Occupied: < 35 years', 'Owner Occupied: < 35 years',
       'Renter Occupied: < 35 years', 'Occupied: 35-44 years',
       'Owner Occupied: 35-44 years', 'Renter Occupied: 35-44 years',
       'Occupied: 45-54 years', 'Owner Occupied: 45-54 years',
       'Renter Occupied: 45-54 years', 'Occupied: 55-64 years',
       'Owner Occupied: 55-64 years', 'Renter Occupied: 55-64 years',
       'Occupied: 65-74 years', 'Owner Occupied: 65-74 years',
       'Renter Occupied: 65-74 years', 'Occupied: 75-84 years',
       'Owner Occupied: 75-84 years', 'Renter Occupied: 75-84 years',
       'Occupied: > 85 years', 'Owner Occupied: > 85 years',
       'Renter Occupied: > 85 years', 'Occupied: Less than High School',
       'Owner Occupied: Less than High School',
       'Renter Occupied: Less than High School',
       'Occupied: High School Graduate',
       'Owner Occupied: High School Graduate',
       'Renter Occupied: High School Graduate',
       'Occupied: Some college or associates degree',
       'Owner Occupied: Some college or associates degree',
       'Renter Occupied: Some college or associates degree',
       'Occupied: Bachelor's degree or higher',
       'Owner Occupied: Bachelor's degree or higher',
       'Renter Occupied: Bachelor's degree or higher'],
      dtype='object', name=0)

In [204]:
# Create a list of all dataframes
dataframes = [df_2011_processed, df_2012_processed]
""", df_2013_processed, df_2014_processed, 
              df_2015_processed, df_2016_processed, df_2017_processed, df_2018_processed, 
              df_2019_processed, df_2020_processed, df_2021_processed, df_2022_processed]"""

# Get the columns of the first dataframe as a reference
reference_columns = set(dataframes[0].columns)

# Check if all dataframes have the same columns as the reference
all_same = all(set(df.columns) == reference_columns for df in dataframes)

if all_same:
    print("All datasets have the same columns.")
else:
    print("Not all datasets have the same columns.")
    
    # Find which datasets have different columns
    for i, df in enumerate(dataframes):
        if set(df.columns) != reference_columns:
            print(f"Dataset {2011 + i} has different columns.")
            
            # Find the differences
            missing = reference_columns - set(df.columns)
            extra = set(df.columns) - reference_columns
            
            if missing:
                print(f"  Missing columns: {missing}")
            if extra:
                print(f"  Extra columns: {extra}")

All datasets have the same columns.

In [205]:
#combined_df = pd.concat([df_2011_processed, df_2012_processed, df_2013_processed, df_2014_processed, df_2015_processed, df_2016_processed, df_2017_processed, df_2018_processed, df_2019_processed, df_2020_processed, df_2021_processed, df_2022_processed], ignore_index=True)

#print("All datasets have been concatenated into one single dataset.")
#combined_df

In [206]:
df_2011_processed.insert(0, 'Year', 2011)
df_2012_processed.insert(0, 'Year', 2012)
df_2013_processed.insert(0, 'Year', 2013)
df_2014_processed.insert(0, 'Year', 2014)
df_2015_processed.insert(0, 'Year', 2015)
df_2016_processed.insert(0, 'Year', 2016)
df_2017_processed.insert(0, 'Year', 2017)
df_2018_processed.insert(0, 'Year', 2018)
df_2019_processed.insert(0, 'Year', 2019)
df_2020_processed.insert(0, 'Year', 2020)
df_2021_processed.insert(0, 'Year', 2021)
df_2022_processed.insert(0, 'Year', 2022)

In [207]:
df_2022_processed

,Year,Occupied Housing Units,Occupied: White,Occupied: Black or African American,Occupied: American Indian and Alaskan Native,Occupied: Asian,Occupied: Native Hawaiian and Other Pacific Islander,Occupied: Some Other Race,Occupied: Two or more races,Occupied: Hispanic or Latino Origin,...,Renter Occupied: 35-44 years,Renter Occupied: 45-54 years,Renter Occupied: 55-64 years,Renter Occupied: 65-74 years,Renter Occupied: 75-84 years,Renter Occupied: > 85 years,Renter Occupied: Less than High School,Renter Occupied: High School Graduate,Renter Occupied: Some college or associates degree,Renter Occupied: Bachelor's degree or higher
0,2022,48754,17887,15922,191,4105,147,5055,5447,11064,...,6239,4939,5760,4095,1463,639,6106,7159,8401,14920

In [208]:
df_2011_processed = df_2011_processed.set_index('Year')
df_2012_processed = df_2012_processed.set_index('Year')
df_2013_processed = df_2013_processed.set_index('Year')
df_2014_processed = df_2014_processed.set_index('Year')
df_2015_processed = df_2015_processed.set_index('Year')
df_2016_processed = df_2016_processed.set_index('Year')
df_2017_processed = df_2017_processed.set_index('Year')
df_2018_processed = df_2018_processed.set_index('Year')
df_2019_processed = df_2019_processed.set_index('Year')
df_2020_processed = df_2020_processed.set_index('Year')
df_2021_processed = df_2021_processed.set_index('Year')
df_2022_processed = df_2022_processed.set_index('Year')

In [209]:
df_2022_processed

,Occupied Housing Units,Occupied: White,Occupied: Black or African American,Occupied: American Indian and Alaskan Native,Occupied: Asian,Occupied: Native Hawaiian and Other Pacific Islander,Occupied: Some Other Race,Occupied: Two or more races,Occupied: Hispanic or Latino Origin,Occupied: White Alone (Not Hispanic or Latino),...,Renter Occupied: 35-44 years,Renter Occupied: 45-54 years,Renter Occupied: 55-64 years,Renter Occupied: 65-74 years,Renter Occupied: 75-84 years,Renter Occupied: > 85 years,Renter Occupied: Less than High School,Renter Occupied: High School Graduate,Renter Occupied: Some college or associates degree,Renter Occupied: Bachelor's degree or higher
Year,,,,,,,,,,,,,,,,,,,,,
2022,48754,17887,15922,191,4105,147,5055,5447,11064,15855,...,6239,4939,5760,4095,1463,639,6106,7159,8401,14920

In [210]:
df_2011_processed

,Occupied Housing Units,Owner Occupied Housing Units,Renter Occupied Housing Units,Occupied: White,Owner Occupied: White,Renter Occupied: White,Occupied: Black or African American,Owner Occupied: Black or African American,Renter Occupied: Black or African American,Occupied: American Indian and Alaskan Native,...,Renter Occupied: Less than High School,Occupied: High School Graduate,Owner Occupied: High School Graduate,Renter Occupied: High School Graduate,Occupied: Some college or associates degree,Owner Occupied: Some college or associates degree,Renter Occupied: Some college or associates degree,Occupied: Bachelor's degree or higher,Owner Occupied: Bachelor's degree or higher,Renter Occupied: Bachelor's degree or higher
Year,,,,,,,,,,,,,,,,,,,,,
2011,36488.0,8774.0,27714.0,1177.5,1272.9,1121.5,1291.3,1230.9,1310.2,19.7,...,599.1,588.6,303.6,649.7,892.8,710.8,963.0,1095.5,1732.4,888.0

In [211]:
dataframes = [df_2011_processed, df_2012_processed, df_2013_processed, df_2014_processed,
              df_2015_processed, df_2016_processed, df_2017_processed, df_2018_processed,
              df_2019_processed, df_2020_processed, df_2021_processed, df_2022_processed]

all_columns = set()
for df in dataframes:
    all_columns.update(df.columns)

In [212]:
all_columns = sorted(list(all_columns))

In [213]:
df_2011_processed = df_2011_processed.reindex(columns=all_columns)
df_2012_processed = df_2012_processed.reindex(columns=all_columns)
df_2013_processed = df_2013_processed.reindex(columns=all_columns)
df_2014_processed = df_2014_processed.reindex(columns=all_columns)
df_2015_processed = df_2015_processed.reindex(columns=all_columns)
df_2016_processed = df_2016_processed.reindex(columns=all_columns)
df_2017_processed = df_2017_processed.reindex(columns=all_columns)
df_2018_processed = df_2018_processed.reindex(columns=all_columns)
df_2019_processed = df_2019_processed.reindex(columns=all_columns)
df_2020_processed = df_2020_processed.reindex(columns=all_columns)
df_2021_processed = df_2021_processed.reindex(columns=all_columns)
df_2022_processed = df_2022_processed.reindex(columns=all_columns)

In [214]:
df_2022_processed

,Occupied Housing Units,Occupied: 35-44 years,Occupied: 45-54 years,Occupied: 55-64 years,Occupied: 65-74 years,Occupied: 75-84 years,Occupied: < 35 years,Occupied: > 85 years,Occupied: American Indian and Alaskan Native,Occupied: Asian,...,Renter Occupied: Black or African American,Renter Occupied: High School Graduate,Renter Occupied: Hispanic or Latino Origin,Renter Occupied: Less than High School,Renter Occupied: Native Hawaiian and Other Pacific Islander,Renter Occupied: Some Other Race,Renter Occupied: Some college or associates degree,Renter Occupied: Two or more races,Renter Occupied: White,Renter Occupied: White Alone (Not Hispanic or Latino)
Year,,,,,,,,,,,,,,,,,,,,,
2022,48754,8225,7542,8787,5832,2278,15092,998,191,4105,...,11950,7159,9979,6106,147,4595,8401,4547,11907,10142

In [215]:
df_2022_processed

,Occupied Housing Units,Occupied: 35-44 years,Occupied: 45-54 years,Occupied: 55-64 years,Occupied: 65-74 years,Occupied: 75-84 years,Occupied: < 35 years,Occupied: > 85 years,Occupied: American Indian and Alaskan Native,Occupied: Asian,...,Renter Occupied: Black or African American,Renter Occupied: High School Graduate,Renter Occupied: Hispanic or Latino Origin,Renter Occupied: Less than High School,Renter Occupied: Native Hawaiian and Other Pacific Islander,Renter Occupied: Some Other Race,Renter Occupied: Some college or associates degree,Renter Occupied: Two or more races,Renter Occupied: White,Renter Occupied: White Alone (Not Hispanic or Latino)
Year,,,,,,,,,,,,,,,,,,,,,
2022,48754,8225,7542,8787,5832,2278,15092,998,191,4105,...,11950,7159,9979,6106,147,4595,8401,4547,11907,10142

In [216]:
combined_df = pd.concat(dataframes, axis=0)

In [217]:
master_columns = sorted(combined_df.columns)  # Create a master column list
dataframes = [df.reindex(columns=master_columns) for df in dataframes]  # Reindex all DataFrames
combined_df = pd.concat(dataframes, axis=0)

In [218]:
combined_df

,Occupied Housing Units,Occupied: 35-44 years,Occupied: 45-54 years,Occupied: 55-64 years,Occupied: 65-74 years,Occupied: 75-84 years,Occupied: < 35 years,Occupied: > 85 years,Occupied: American Indian and Alaskan Native,Occupied: Asian,...,Renter Occupied: Black or African American,Renter Occupied: High School Graduate,Renter Occupied: Hispanic or Latino Origin,Renter Occupied: Less than High School,Renter Occupied: Native Hawaiian and Other Pacific Islander,Renter Occupied: Some Other Race,Renter Occupied: Some college or associates degree,Renter Occupied: Two or more races,Renter Occupied: White,Renter Occupied: White Alone (Not Hispanic or Latino)
Year,,,,,,,,,,,,,,,,,,,,,
2011,36488.0,509.0,536.4,549.8,235.5,166.3,1042.4,60.6,19.7,178.8,...,1310.2,649.7,688.4,599.1,0.0,394.7,963.0,89.6,1121.5,910.0
2012,36962.0,495.2,557.6,564.7,260.3,166.8,1006.9,48.7,19.6,190.6,...,1276.8,673.0,713.6,579.3,0.0,392.9,931.0,85.8,1136.3,911.5
2013,37122.0,494.5,558.5,466.9,273.1,166.0,985.7,55.7,18.1,192.7,...,1246.4,661.0,739.5,590.0,0.0,452.8,782.4,88.3,1005.7,788.6
2014,37804.0,497.7,548.9,490.5,280.2,156.0,971.3,55.1,21.2,190.1,...,1241.0,693.4,735.4,560.4,0.0,457.3,769.0,89.6,990.8,764.2
2015,38700.0,489.8,551.5,479.2,297.0,154.4,974.1,53.9,17.6,189.9,...,1215.4,699.4,773.1,552.1,1.1,450.9,768.7,91.3,1017.0,770.5
2016,38745.0,490.7,567.3,493.6,326.6,149.4,929.0,43.7,14.5,187.3,...,1236.6,694.6,791.2,578.4,1.1,440.2,734.8,105.4,998.6,775.1
2017,38926.0,6238.0,6808.0,6385.0,4471.0,2177.0,12299.0,548.0,199.0,2708.0,...,11363.0,6547.0,7845.0,5597.0,18.0,4102.0,6897.0,1184.0,10259.0,8066.0
2018,39363.0,6353.0,6765.0,6659.0,4563.0,2221.0,12247.0,555.0,247.0,2683.0,...,11386.0,6924.0,8426.0,5585.0,18.0,4185.0,6866.0,1203.0,10316.0,7861.0
2019,39343.0,6698.0,6787.0,6559.0,4514.0,2134.0,11949.0,702.0,221.0,2915.0,...,11539.0,6821.0,8195.0,5503.0,101.0,4129.0,6970.0,1162.0,10060.0,7844.0
2020,48637.0,8270.0,8039.0,8201.0,5930.0,2181.0,15003.0,1013.0,302.0,4150.0,...,12388.0,7004.0,9893.0,6422.0,76.0,4684.0,8017.0,2288.0,12666.0,9979.0
2021,48490.0,8398.0,7555.0,8507.0,5817.0,2244.0,14982.0,987.0,360.0,3947.0,...,11970.0,7359.0,10134.0,6176.0,119.0,4758.0,8312.0,3500.0,12563.0,10319.0
2022,48754.0,8225.0,7542.0,8787.0,5832.0,2278.0,15092.0,998.0,191.0,4105.0,...,11950.0,7159.0,9979.0,6106.0,147.0,4595.0,8401.0,4547.0,11907.0,10142.0

In [219]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\asraa\appdata\local\programs\python\python38\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\asraa\appdata\local\programs\python\python38\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution -atplotlib (c:\users\asraa\appdata\local\programs\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\asraa\appdata\local\programs\python\python38\lib\site-packages)
WARNING: Ignoring invalid distribution -atplotlib (c:\users\asraa\appdata\local\programs\python\python38\lib\site-packages)

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [220]:
combined_df.to_excel("processed_data.xlsx", index=True)

### Separating By Housing Type, such that instead of separate columns for "Occupied - Under 35", "Owner Occupied - Under 35" and "Renter Occupied - Under 35" for the year 2011, I will have 3 rows for the year 2011, one for each type of housing (occupied, owner occupied, renter occupied)

In [221]:
import pandas as pd

df = pd.read_excel('processed_data.xlsx')

In [222]:
df_melted = df.melt(id_vars=['Year'], var_name='Category', value_name='Value')

In [223]:
def determine_housing_type(category):
    if category.startswith('Owner Occupied'):
        return 'Owner Occupied'
    elif category.startswith('Renter Occupied'):
        return 'Renter Occupied'
    else:
        return 'Occupied'

# Apply the function to create the new 'Housing Type' column
df_melted['Housing Type'] = df_melted['Category'].apply(determine_housing_type)

In [224]:
categories = set()
for col in df.columns:
    if col != 'Year' and ':' in col:
        categories.add(col.split(': ', 1)[1])

# Function to reshape the dataframe
def reshape_dataframe(df):
    reshaped_data = []
    for _, row in df.iterrows():
        year = row['Year']
        # Define totals for each housing type
        totals = {
            'Occupied': row['Occupied Housing Units'],
            'Owner Occupied': row['Owner Occupied Housing Units'],
            'Renter Occupied': row['Renter Occupied Housing Units']
        }
        for housing_type in ['Occupied', 'Owner Occupied', 'Renter Occupied']:
            new_row = {'Year': year, 'Housing Type': housing_type, 'Total': totals[housing_type]}
            for category in categories:
                col_name = f"{housing_type}: {category}"
                if col_name in df.columns:
                    new_row[category] = row[col_name]
                else:
                    new_row[category] = None
            reshaped_data.append(new_row)
    return pd.DataFrame(reshaped_data)

# Reshape the dataframe
reshaped_df = reshape_dataframe(df)

# Reorder columns
column_order = ['Year', 'Housing Type', 'Total'] + sorted(list(categories))
reshaped_df = reshaped_df[column_order]

# Display the reshaped dataframe
reshaped_df

,Year,Housing Type,Total,35-44 years,45-54 years,55-64 years,65-74 years,75-84 years,< 35 years,> 85 years,...,Black or African American,High School Graduate,Hispanic or Latino Origin,Less than High School,Native Hawaiian and Other Pacific Islander,Some Other Race,Some college or associates degree,Two or more races,White,White Alone (Not Hispanic or Latino)
0,2011.0,Occupied,36488.0,509.0,536.4,549.8,235.5,166.3,1042.4,60.6,...,1291.3,588.6,580.7,523.1,1.5,339.4,892.8,91.9,1177.5,999.1
1,2011.0,Owner Occupied,8774.0,575.3,638.6,598.0,289.2,207.7,595.1,96.6,...,1230.9,303.6,274.3,253.2,4.6,192.5,710.8,86.6,1272.9,1182.0
2,2011.0,Renter Occupied,27714.0,480.6,547.7,493.0,202.7,132.5,1187.0,56.7,...,1310.2,649.7,688.4,599.1,0.0,394.7,963.0,89.6,1121.5,910.0
3,2012.0,Occupied,36962.0,495.2,557.6,564.7,260.3,166.8,1006.9,48.7,...,1276.2,609.5,605.9,514.5,1.4,334.5,884.4,86.5,1190.8,994.7
4,2012.0,Owner Occupied,8344.0,502.4,686.3,681.8,311.1,201.3,562.8,54.0,...,1269.1,301.7,278.6,334.9,3.9,182.7,621.8,76.8,1271.1,1172.7
5,2012.0,Renter Occupied,28618.0,472.7,556.3,500.3,231.5,141.4,1150.9,46.7,...,1276.8,673.0,713.6,579.3,0.0,392.9,931.0,85.8,1136.3,911.5
6,2013.0,Occupied,37122.0,494.5,558.5,466.9,273.1,166.0,985.7,55.7,...,1244.2,607.7,630.0,522.0,1.2,380.7,746.7,92.5,1070.9,883.1
7,2013.0,Owner Occupied,8593.0,481.4,741.1,632.1,322.2,235.0,506.0,82.8,...,1186.5,374.7,327.5,309.1,3.4,196.8,606.9,81.5,1327.5,1196.0
8,2013.0,Renter Occupied,28529.0,487.0,538.1,399.1,249.3,131.5,1147.0,48.1,...,1246.4,661.0,739.5,590.0,0.0,452.8,782.4,88.3,1005.7,788.6
9,2014.0,Occupied,37804.0,497.7,548.9,490.5,280.2,156.0,971.3,55.1,...,1239.4,641.8,642.9,501.5,0.0,396.5,734.2,92.0,1060.8,866.9
10,2014.0,Owner Occupied,8508.0,493.7,574.6,666.2,361.2,213.5,501.0,89.7,...,1186.2,412.4,292.4,242.4,0.0,149.9,591.4,105.3,1291.4,1181.6
11,2014.0,Renter Occupied,29296.0,493.9,531.8,422.9,254.2,131.4,1118.8,47.3,...,1241.0,693.4,735.4,560.4,0.0,457.3,769.0,89.6,990.8,764.2
12,2015.0,Occupied,38700.0,489.8,551.5,479.2,297.0,154.4,974.1,53.9,...,1223.4,640.2,672.8,488.0,1.0,388.1,751.7,96.4,1083.4,870.4
13,2015.0,Owner Occupied,8925.0,484.8,590.2,661.8,357.8,249.6,480.5,75.4,...,1207.7,391.3,319.6,220.0,0.0,157.9,679.3,136.3,1247.4,1124.8
14,2015.0,Renter Occupied,29775.0,483.2,521.4,420.5,272.2,123.8,1132.8,46.5,...,1215.4,699.4,773.1,552.1,1.1,450.9,768.7,91.3,1017.0,770.5
15,2016.0,Occupied,38745.0,490.7,567.3,493.6,326.6,149.4,929.0,43.7,...,1239.1,638.8,683.0,501.9,1.0,381.0,728.9,105.4,1071.5,880.6
16,2016.0,Owner Occupied,9016.0,480.4,608.4,663.8,419.3,174.0,501.8,52.2,...,1192.2,410.6,300.7,201.6,0.0,153.6,657.5,142.2,1249.8,1167.4
17,2016.0,Renter Occupied,29729.0,492.6,535.3,447.7,282.3,135.5,1068.0,38.7,...,1236.6,694.6,791.2,578.4,1.1,440.2,734.8,105.4,998.6,775.1
18,2017.0,Occupied,38926.0,6238.0,6808.0,6385.0,4471.0,2177.0,12299.0,548.0,...,14777.0,7688.0,8755.0,6147.0,18.0,4606.0,8882.0,1536.0,15082.0,12622.0
19,2017.0,Owner Occupied,9585.0,1528.0,2037.0,2057.0,1561.0,540.0,1686.0,176.0,...,3414.0,1141.0,910.0,550.0,0.0,504.0,1985.0,352.0,4823.0,4556.0
20,2017.0,Renter Occupied,29341.0,4710.0,4771.0,4328.0,2910.0,1637.0,10613.0,372.0,...,11363.0,6547.0,7845.0,5597.0,18.0,4102.0,6897.0,1184.0,10259.0,8066.0
21,2018.0,Occupied,39363.0,6353.0,6765.0,6659.0,4563.0,2221.0,12247.0,555.0,...,15009.0,8033.0,9349.0,6145.0,18.0,4619.0,9122.0,1544.0,15243.0,12457.0
22,2018.0,Owner Occupied,9795.0,1686.0,1975.0,2142.0,1607.0,535.0,1666.0,184.0,...,3623.0,1109.0,923.0,560.0,0.0,434.0,2256.0,341.0,4927.0,4596.0
23,2018.0,Renter Occupied,29568.0,4667.0,4790.0,4517.0,2956.0,1686.0,10581.0,371.0,...,11386.0,6924.0,8426.0,5585.0,18.0,4185.0,6866.0,1203.0,10316.0,7861.0
24,2019.0,Occupied,39343.0,6698.0,6787.0,6559.0,4514.0,2134.0,11949.0,702.0,...,15153.0,7998.0,9168.0,6117.0,101.0,4526.0,8980.0,1547.0,14880.0,12262.0
25,2019.0,Owner Occupied,9756.0,1716.0,1965.0,2130.0,1601.0,645.0,1498.0,201.0,...,3614.0,1177.0,973.0,614.0,0.0,397.0,2010.0,385.0,4820.0,4418.0
26,2019.0,Renter Occupied,29587.0,4982.0,4822.0,4429.0,2913.0,1489.0,10451.0,501.0,...,11539.0,6821.0,8195.0,5503.0,101.0,4129.0,6970.0,1162.0,10060.0,7844.0
27,2020.0,Occupied,48637.0,8270.0,8039.0,8201.0,5930.0,2181.0,15003.0,1013.0,...,17103.0,8718.0,10934.0,7214.0,76.0,5136.0,10387.0,2929.0,18941.0,15910.0
28,2020.0,Owner Occupied,12921.0,2425.0,2592.0,3047.0,1958.0,624.0,1899.0,376.0,...,4715.0,1714.0,1041.0,792.0,0.0,452.0,2370.0,641.0,6275.0,5931.0
29,2020.0,Renter Occupied,35716.0,5845.0,5447.0,5154.0,3972.0,1557.0,13104.0,637.0,...,12388.0,7004.0,9893.0,6422.0,76.0,4684.0,8017.0,2288.0,12666.0,9979.0
30,2021.0,Occupied,48490.0,8398.0,7555.0,8507.0,5817.0,2244.0,14982.0,987.0,...,16212.0,8925.0,11137.0,7069.0,119.0,5205.0,10354.0,4243.0,18404.0,15915.0
31,2021.0,Owner Occupied,12082.0,2029.0,2380.0,3005.0,1842.0,682.0,1755.0,389.0,...,4242.0,1566.0,1003.0,893.0,0.0,447.0,2042.0,743.0,5841.0,5596.0
32,2021.0,Renter Occupied,36408.0,6369.0,5175.0,5502.0,3975.0,1562.0,13227.0,598.0,...,11970.0,7359.0,10134.0,6176.0,119.0,4758.0,8312.0,3500.0,12563.0,10319.0
33,2022.0,Occupied,48754.0,8225.0,7542.0,8787.0,5832.0,2278.0,15092.0,998.0,...,15922.0,8690.0,11064.0,6987.0,147.0,5055.0,10314.0,5447.0,17887.0,15855.0
34,2022.0,Owner Occupied,12168.0,1986.0,2603.0,3027.0,1737.0,815.0,1641.0,359.0,...,3972.0,1531.0,1085.0,881.0,0.0,460.0,1913.0,900.0,5980.0,5713.0
35,2022.0,Renter Occupied,36586.0,6239.0,4939.0,5760.0,4095.0,1463.0,13451.0,639.0,...,11950.0,7159.0,9979.0,6106.0,147.0,4595.0,8401.0,4547.0,11907.0,10142.0

In [225]:
reshaped_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 23 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Year                                        36 non-null     float64
 1   Housing Type                                36 non-null     object
 2   Total                                       36 non-null     float64
 3   35-44 years                                 36 non-null     float64
 4   45-54 years                                 36 non-null     float64
 5   55-64 years                                 36 non-null     float64
 6   65-74 years                                 36 non-null     float64
 7   75-84 years                                 36 non-null     float64
 8   < 35 years                                  36 non-null     float64
 9   > 85 years                                  36 non-null     float64
 10  American Indian and Alaskan Native          36 non-null     float64
 11  Asian                                       36 non-null     float64
 12  Bachelor's degree or higher                 36 non-null     float64
 13  Black or African American                   36 non-null     float64
 14  High School Graduate                        36 non-null     float64
 15  Hispanic or Latino Origin                   36 non-null     float64
 16  Less than High School                       36 non-null     float64
 17  Native Hawaiian and Other Pacific Islander  36 non-null     float64
 18  Some Other Race                             36 non-null     float64
 19  Some college or associates degree           36 non-null     float64
 20  Two or more races                           36 non-null     float64
 21  White                                       36 non-null     float64
 22  White Alone (Not Hispanic or Latino)        36 non-null     float64
dtypes: float64(22), object(1)
memory usage: 6.6+ KB

In [226]:
reshaped_df = reshaped_df.astype({col: 'int' for col in reshaped_df.select_dtypes(include=['float64']).columns})

In [228]:
reshaped_df.to_excel("reshaped_data.xlsx", index=True)

In [ ]:
reshaped_df.columns

Index(['Year', 'Housing Type', 'Total', '35-44 years', '45-54 years',
       '55-64 years', '65-74 years', '75-84 years', '< 35 years', '> 85 years',
       'American Indian and Alaskan Native', 'Asian',
       'Bachelor's degree or higher', 'Black or African American',
       'High School Graduate', 'Hispanic or Latino Origin',
       'Less than High School', 'Native Hawaiian and Other Pacific Islander',
       'Some Other Race', 'Some college or associates degree',
       'Two or more races', 'White', 'White Alone (Not Hispanic or Latino)'],
      dtype='object')

In [ ]:
reshaped_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 23 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Year                                        36 non-null     float64
 1   Housing Type                                36 non-null     object
 2   Total                                       36 non-null     float64
 3   35-44 years                                 36 non-null     float64
 4   45-54 years                                 36 non-null     float64
 5   55-64 years                                 36 non-null     float64
 6   65-74 years                                 36 non-null     float64
 7   75-84 years                                 36 non-null     float64
 8   < 35 years                                  36 non-null     float64
 9   > 85 years                                  36 non-null     float64
 10  American Indian and Alaskan Native          36 non-null     float64
 11  Asian                                       36 non-null     float64
 12  Bachelor's degree or higher                 36 non-null     float64
 13  Black or African American                   36 non-null     float64
 14  High School Graduate                        36 non-null     float64
 15  Hispanic or Latino Origin                   36 non-null     float64
 16  Less than High School                       36 non-null     float64
 17  Native Hawaiian and Other Pacific Islander  36 non-null     float64
 18  Some Other Race                             36 non-null     float64
 19  Some college or associates degree           36 non-null     float64
 20  Two or more races                           36 non-null     float64
 21  White                                       36 non-null     float64
 22  White Alone (Not Hispanic or Latino)        36 non-null     float64
dtypes: float64(22), object(1)
memory usage: 6.6+ KB